---

- name: install the latest version of influxdb
  yum:
    name: influxdb
    state: latest

- name: enable and start influxdb
  systemd:
    name: influxdb
    state: started
    enabled: yes

# CREATE DATABSE
- name: Create metrics database for storing postgres server info
  shell:
    cmd: influx -execute 'create database metrics with DURATION 2d'

# CREATE USER
- name: Create influxdb user for telegraf 
  shell:
    cmd: influx -execute "create user dbmon with password 'jocasta' "

# GRANT USER PRIVILEGES
- name: 
  shell:
    cmd: influx -execute 'grant write on metrics to dbmon'


