# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "pgserver" do |pgserver|
    pgserver.vm.box = "centos/7"
    pgserver.vm.hostname = 'pgserver'

    pgserver.vm.network :private_network, ip: "192.168.56.101"

    pgserver.vm.provision "shell", path: "postgres_provision.sh"

    pgserver.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "pgserver"]
    end
  end

  config.vm.define "pgserver2" do |pgserver2|
    pgserver2.vm.box = "centos/7"
    pgserver2.vm.hostname = 'pgserver2'

    pgserver2.vm.network :private_network, ip: "192.168.56.102"

    pgserver2.vm.provision "shell", path: "postgres_provision.sh"

    pgserver2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "pgserver2"]
    end
  end



  config.vm.define "influxdb" do |influxdb|
    influxdb.vm.box = "centos/7"
    influxdb.vm.hostname = 'influxdb'

    influxdb.vm.network :private_network, ip: "192.168.56.103"

    influxdb.vm.provision "shell", path: "influxdb_provision.sh"

    influxdb.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "influxdb"]
    end
  end


  config.vm.define "grafana" do |grafana|
    grafana.vm.box = "centos/7"
    grafana.vm.hostname = 'grafana'

    grafana.vm.network :private_network, ip: "192.168.56.104"

    grafana.vm.provision "shell", path: "grafana_provision.sh"

    grafana.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "grafana"]
    end
  end


end
