# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#

PRIVATE_KEY = "~/.ssh/id_rsa"
PUBLIC_KEY  = '~/.ssh/id_rsa.pub'

Vagrant.configure("2") do |config|

## LOOP THROUGH AND CREATE MULTIPLE SERVERS
(1..3).each do |i|
        config.vm.define "node-#{i}" do |node|
                node.vm.box = "centos/7"
                node.vm.hostname = "node-#{i}"
                node.vm.network :private_network, ip: "192.168.56.10#{i}"
                # node.vm.provision "shell", path: "server_provision.sh", args: "#{i}"

                config.ssh.insert_key = false
                config.ssh.private_key_path = [PRIVATE_KEY,
                "~/.vagrant.d/insecure_private_key"]
                config.vm.provision "file", source: PUBLIC_KEY, destination:
                "~/.ssh/authorized_keys"


                node.vm.provider :virtualbox do |v|
                        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                        v.customize ["modifyvm", :id, "--memory", 1024]
                        v.customize ["modifyvm", :id, "--name", "node-#{i}"]
                end


        end
end

end
