# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|


## LOOP THROUGH AND CREATE MULTIPLE SERVERS
(5..6).each do |i|
        config.vm.define "node-#{i}" do |node|
                node.vm.box = "centos/7"
                node.vm.hostname = "node-#{i}"
                node.vm.network :private_network, ip: "192.168.56.10#{i}"
                node.vm.provision "shell", path: "server_provision.sh", args: "#{i}"
                node.vm.provision "shell", path: "ssl_test.sh", args: "#{i}"

                node.vm.provider :virtualbox do |v|
                        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                        v.customize ["modifyvm", :id, "--memory", 1024]
                        v.customize ["modifyvm", :id, "--name", "node-#{i}"]
                end


        end
end

end

