# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|


# If you don't want the plugin to remove the host entry
# with halt / suspend > then add this to Vagrantfile
#config.hostsupdater.remove_on_suspend = false

## SETTINGS FOR HOSTMANAGER PLUGIN
config.hostmanager.enabled = true
config.hostmanager.manage_host = true
config.hostmanager.manage_guest = true
config.hostmanager.ignore_private_ip = false
config.hostmanager.include_offline = true



###########################################
#                                         #
#     CREATE ANSIBLE MASTER               #
#                                         #
###########################################

  config.vm.define "ansible-master" do |ans|
    ans.vm.box = "centos/7"
    ans.vm.hostname = "ansible-master"
    ans.vm.network :private_network, ip: "192.170.76.2"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision_host.yml"
  end

  ans.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--cpus", 1]
    v.customize ["modifyvm", :id, "--name", "ansible-master"]
  end

end


###########################################
#                                         #
#     CREATE PGBOUNCER NODES              #
#                                         #
###########################################

(1..1).each do |i|
  config.vm.define "pgbouncer-#{i}" do |ans|
    ans.vm.box = "centos/7"
    ans.vm.hostname = "pgbouncer-#{i}"
    ans.vm.network :private_network, ip: "192.170.76.10#{i}"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision_host.yml"
  end

  ans.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--cpus", 1]
    v.customize ["modifyvm", :id, "--name", "pgbouncer-#{i}"]
  end

end

end

###########################################
#                                         #
#     CREATE POSTGRES NODES               #
#                                         #
###########################################


## LOOP THROUGH AND CREATE MULTIPLE SERVERS
(1..1).each do |i|
        config.vm.define "postgres-node-#{i}" do |node|
                node.vm.box = "centos/7"
                node.vm.hostname = "postgres-node-#{i}"
                node.vm.network :private_network, ip: "192.170.76.20#{i}"

## SET DISK PATHS
db_disk = "/home/mike/Vagrant_VM_disk/Vagrant_disk-db-hap-pbouncer-#{i}.vdi"
log_disk = "/home/mike/Vagrant_VM_disk/Vagrant_disk-log-hap-pbouncer-#{i}.vdi"
dbtemp_disk = "/home/mike/Vagrant_VM_disk/Vagrant_disk-dbtemp-hap-pbouncer-#{i}.vdi"

                node.vm.provider :virtualbox do |v|
                        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                        v.customize ["modifyvm", :id, "--memory", 2048]
                        v.customize ["modifyvm", :id, "--name", "node-#{i}"]
                        v.customize ["modifyvm", :id, "--cableconnected1", "on"]
                        unless FileTest.exist?(db_disk)
                        v.customize ["storagectl", :id, "--name", "SAS Controller", "--add", "sas", '--portcount', 4]
                        v.customize ["createhd", "--filename", db_disk, "--size", 5 * 1024]
                        v.customize ["createhd", "--filename", log_disk, "--size", 5 * 1024]
                        v.customize ["createhd", "--filename", dbtemp_disk, "--size", 5 * 1024]
                        v.customize ["storageattach", :id, "--storagectl", "SAS Controller", "--port", 1, "--type", "hdd", "--medium", db_disk]
                        v.customize ["storageattach", :id, "--storagectl", "SAS Controller", "--port", 2, "--type", "hdd", "--medium", log_disk]
                        v.customize ["storageattach", :id, "--storagectl", "SAS Controller", "--port", 3, "--type", "hdd", "--medium", dbtemp_disk]
                        end
                  end
                end

        end
end
