---

  - name: Install epel Repository
    yum_repository:
      name: EPEL
      description: epel
      file: external_repos
      state: present
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: true
      gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
