# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    master.vm.hostname = 'master'

    master.vm.network :private_network, ip: "192.168.56.101"

    master.vm.provision "shell", path: "master_provision.sh"

    master.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "master"]
    end
  end

  config.vm.define "slave" do |slave|
    slave.vm.box = "centos/7"
    slave.vm.hostname = 'slave'

    slave.vm.network :private_network, ip: "192.168.56.102"

    slave.vm.provision "shell", path: "slave_provision.sh"

    slave.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "slave"]
    end
  end

config.vm.define "barman" do |barman|
    barman.vm.box = "centos/7"
    barman.vm.hostname = 'barman'

    barman.vm.network :private_network, ip: "192.168.56.103"

    barman.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "barman"]
    end
  end


end
