---
- hosts: node-2
  remote_user: root
  gather_facts: no
  become: yes

  tasks:

  - name: add postgres server ssh key to barman authorized_key
    authorized_key:
      user: barman
      state: present
      key: "{{ lookup('file','keys/postgres/postgres-id_rsa.pub')}}"

  - name: remove local copy of postgres server key
    local_action: command chmod 777 keys/postgres/postgres-id_rsa.pub

  - name: remove local copy of postgres server key
    local_action: command rm keys/postgres/postgres-id_rsa.pub


