---
- hosts: "{{ target }}"
  remote_user: root
  gather_facts: no
  become: yes

  tasks:

    - name: Set Postgres Version
      command: bash -c "ls -1 /db/PostgreSQL/ | sort -r | head -1"
      register: version
    - set_fact: version='{{version.stdout}}'

    - name: Create Old Config dir if not already present
      file:
        path: /db/PostgreSQL/{{version}}/data/old_configs
        state: directory
        owner: postgres
        group: postgres
        mode: 0744

    - name: Remove old Barman & python psycopg2 packages for local backups
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - barman
        - python-psycopg2
        - python2-psycopg2
        - python-barman

    - name: Install barman-cli for wal streaming
      yum:
        name: barman-cli
        state: present

    - name: Repoint barman with barman-wal-archive
      lineinfile:
        path: /db/PostgreSQL/{{version}}/data/postgresql.conf
        backup: yes
        regexp: "^archive_command"
        line: "archive_command = 'barman-wal-archive em-vrgi-mana03.prodev.ros.gov.uk {{ inventory_hostname }} %p' "
        state: present
      notify: Reload PostgreSQL

    - name: Create streaming_barman user, set MD5-hashed password, grant privs
      postgresql_user:
        name: streaming_barman
        password: md50f8dcb89fe1a95379f56832f9dffb256
        role_attr_flags: REPLICATION

    - name: Create barman superuser, set MD5-hashed password, grant privs
      postgresql_user:
        name: barman
        password: md50f8dcb89fe1a95379f56832f9dffb256
        role_attr_flags: SUPERUSER


    - name: Modify pg_hba.conf > Add Barman Server 
      lineinfile:
        path: /db/PostgreSQL/{{version}}/data/pg_hba.conf
        backup: yes
        line: |
          
          ## ProDev Barman backup server
          host    all             all          10.253.2.254/32            md5
          
          ## Barman Streaming
          host    replication     streaming_barman  10.253.2.254/32        md5 
        state: present
      notify: Reload PostgreSQL


    - name: Move backed up configs to old_config directory
      shell: mv /db/PostgreSQL/{{version}}/data/*~  /db/PostgreSQL/{{version}}/data/old_configs

    - name: Fetch ssh key from postgres host
      fetch:
        src: "/var/lib/pgsql/.ssh/id_rsa.pub"
        dest: "keys/postgres/{{ inventory_hostname }}-id_rsa.pub"
        flat: yes

    - name: add barman server ssh key to postgres authorized_key 
      authorized_key:
        user: postgres
        state: present
        key: "{{ lookup('file','keys/barman/barman-dev-id_rsa.pub')}}"

  handlers:
  - name: Reload PostgreSQL
    command: "systemctl reload postgresql*"

