---
# file: setup_barman_server.yml
- hosts: "{{ target }}"
  gather_facts: False
  remote_user: root
  roles:
  - { role: postgresql_add_repo }
  - { role: influxdata_add_repo }
  - { role: telegraf_install }
  vars_files:
  - group_vars/all.yml
