---
- hosts: node-1
  remote_user: root
  gather_facts: no
  become: yes

  tasks:

    - name: Find postgresql.conf
      find: 
        paths: /db/PostgreSQL
        patterns: 'postgresql.conf'
        recurse: yes
        depth: 3
      register: postgresql_conf_find

    - name: Modify found postgresql.conf
      lineinfile:
        path: /db/PostgreSQL/12/data/postgresql.conf
        backup: yes
        regexp: "#TEST"
        line: "archive_command = '/bin/true' "
        state: present
      notify: Reload PostgreSQL

  handlers:
  - name: Reload PostgreSQL
    command: "systemctl reload postgresql*"

