# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|


config.vm.define "grav" do |grav|
    grav.vm.box = "centos/7"
    grav.vm.hostname = 'grav'

    grav.vm.network :private_network, ip: "192.168.56.101"

    grav.vm.provision "shell", path: "server_provision.sh"

    grav.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "grav"]
    end
  end



end
