---

## TEST Postgres YUM REPO


- hosts: test
  gather_facts: False

  tasks:
  - name: Install epel Repository
    yum_repository:
      name: EPEL
      description: epel
      file: external_repos
      state: present
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

  - name: Install PostgreSQL Centos Repository
    yum:
      name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: present
