---

## TEST INSTALL PACKAGES


- hosts: test
  gather_facts: False

  tasks:
    - name: Install PostgreSQL Packages
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - postgresql{{ pg_ver }}-server
        - postgresql{{ pg_ver }}-contrib
        - postgresql{{ pg_ver }}-libs
        - postgresql{{ pg_ver }}

