---
- hosts: node-1
  remote_user: root
  gather_facts: no
  become: yes

  tasks:

    - name: Set Postgres Version
      command: bash -c "ls -1 /db/PostgreSQL/ | sort -r | head -1"
      register: version
    - set_fact: version='{{version.stdout}}'

    - name: Create Old Config dir if not already present
      file:
        path: /db/PostgreSQL/{{version}}/data/old_configs
        state: directory
        owner: postgres
        group: postgres
        mode: 0744

    - name: Remove old Barman & python psycopg2 packages for local backups
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - barman
        - python-psycopg2
        - python2-psycopg2
        - python-barman

    - name: Install barman-cli for wal streaming
      yum:
        name: barman-cli
        state: present

    - name: Repoint barman with barman-wal-archive
      lineinfile:
        path: /db/PostgreSQL/{{version}}/data/postgresql.conf
        backup: yes
        regexp: "^archive_command"
        line: "archive_command = 'barman-wal-archive em-vrgi-mana03.prodev.ros.gov.uk {{ inventory_hostname }} %p' "
        state: present
      notify: Reload PostgreSQL

    - name: Create streaming_barman user, set MD5-hashed password, grant privs
      postgresql_user:
        name: streaming_barman
        password: md59543f1d82624df2b31672ec0f7050460
        role_attr_flags: REPLICATION

    - name: Modify pg_hba.conf > Add Barman Server 
      lineinfile:
        path: /db/PostgreSQL/{{version}}/data/pg_hba.conf
        backup: yes
        line: |
          
          ## ProDev Barman backup server
          hostssl    all             all          10.253.2.254/32            md5
          
          ## Barman Streaming
          hostssl    replication     streaming_barman  10.253.2.254/32        md5 
        state: present
      notify: Reload PostgreSQL


    - name: Move backup to old_config directory
      shell: | 
          if test -f /db/PostgreSQL/{{version}}/data/*~ ; then
          mv /db/PostgreSQL/{{version}}/data/*~  /db/PostgreSQL/{{version}}/data/old_configs
          fi

  handlers:
  - name: Reload PostgreSQL
    command: "systemctl reload postgresql*"

