# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

config.vm.boot_timeout = 30

## LOOP THROUGH AND CREATE MULTIPLE SERVERS
(1..3).each do |i|
        config.vm.define "node-#{i}" do |node|
                node.vm.box = "centos/7"
                node.vm.hostname = "node-#{i}"
                node.vm.network :private_network, ip: "192.168.56.10#{i}"
                ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
                node.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
                node.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
          

                node.vm.provider :virtualbox do |v|
                        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                        v.customize ["modifyvm", :id, "--memory", 1024]
                        v.customize ["modifyvm", :id, "--name", "node-#{i}"]
                        v.customize ["modifyvm", :id, "--cableconnected1", "on"]
                end


        end
end

end

