# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

config.vm.boot_timeout = 30
config.hostsupdater.remove_on_suspend = false

## LOOP THROUGH AND CREATE MULTIPLE SERVERS
(1..4).each do |i|
        config.vm.define "node-#{i}" do |node|
                node.vm.box = "centos/7"
                node.vm.hostname = "node-#{i}"
                node.vm.network :private_network, ip: "192.168.56.10#{i}"
                ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
                node.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
                node.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"

## SET DISK PATHS
db_disk = "/home/mike/Vagrant_VM_disk/Vagrant_disk-db-#{i}.vdi"
log_disk = "/home/mike/Vagrant_VM_disk/Vagrant_disk-log-#{i}.vdi"
dbtemp_disk = "/home/mike/Vagrant_VM_disk/Vagrant_disk-dbtemp-#{i}.vdi"

                node.vm.provider :virtualbox do |v|
                        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                        v.customize ["modifyvm", :id, "--memory", 1024]
                        v.customize ["modifyvm", :id, "--name", "node-#{i}"]
                        v.customize ["modifyvm", :id, "--cableconnected1", "on"]
                        unless FileTest.exist?(db_disk)
                        v.customize ["storagectl", :id, "--name", "SAS Controller", "--add", "sas", '--portcount', 4]
                        v.customize ["createhd", "--filename", db_disk, "--size", 5 * 1024]
                        v.customize ["createhd", "--filename", log_disk, "--size", 5 * 1024]
                        v.customize ["createhd", "--filename", dbtemp_disk, "--size", 5 * 1024]
                        v.customize ["storageattach", :id, "--storagectl", "SAS Controller", "--port", 1, "--type", "hdd", "--medium", db_disk]
                        v.customize ["storageattach", :id, "--storagectl", "SAS Controller", "--port", 2, "--type", "hdd", "--medium", log_disk]
                        v.customize ["storageattach", :id, "--storagectl", "SAS Controller", "--port", 3, "--type", "hdd", "--medium", dbtemp_disk]
                        end
                  end
                end


        end
end
