---

- name: install the latest version of telegraf
  yum:
    name: telegraf
    state: latest

- name: Add Telegraf.conf template
  template:
    src: "templates/telegraf.conf.j2"
    dest: "/etc/telegraf/telegraf.conf"
    owner: root
    group: root
    mode: 644
    backup: yes

- name: enable and start telegraf
  systemd:
    name: telegraf
    state: restarted
    enabled: yes



