# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "server1" do |server1|
    server1.vm.box = "centos/7"
    server1.vm.hostname = 'server1'

    server1.vm.network :private_network, ip: "192.168.56.101"

    server1.vm.provision "shell", path: "server_provision.sh", args: "'3'"

    server1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "server1"]
    end
  end

  config.vm.define "server2" do |server2|
    server2.vm.box = "centos/7"
    server2.vm.hostname = 'server2'

    server2.vm.network :private_network, ip: "192.168.56.102"

    server2.vm.provision "shell", path: "server_provision.sh"

    server2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "server2"]
    end
  end


  config.vm.define "server3" do |server3|
    server3.vm.box = "centos/7"
    server3.vm.hostname = 'server3'

    server3.vm.network :private_network, ip: "192.168.56.103"

    server3.vm.provision "shell", path: "server_provision.sh"

    server3.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "server3"]
    end
  end





  config.vm.define "barman" do |barman|
    barman.vm.box = "centos/7"
    barman.vm.hostname = 'barman'

    barman.vm.network :private_network, ip: "192.168.56.104"

    barman.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "barman"]
    end
  end


end
